### PR TITLE
Port the wasi-filesystem API to the new wit format.

### PR DESCRIPTION
**Pull request by sunfishcode**
This makes a number of changes, to make use of interface-types features such
as expected, variant types, and resources. The change to use resources in
particular means that filesystem functions are now methods of the descriptor
resource. Since this means renaming everything, take this opportunity to
introduce a new naming conventions, with _at being used for functions that
take dirfd+path arguments.
    
This also eliminates the rights concept what was present in earlier versions
of WASI, has has discussed in #31. This required adding new flags to open_at,
so while here, this also adds basic chmod-like support, as discussed in #33.
    
And, this removes support for readdir seeking (seekdir/telldir), as discussed
in #7.
  
And it adds a fifo file type and a more general socket type, as discussed in #4.

### CODE REVIEW

**Comment by sunfishcode** [comment]
The new content here is based on [this proposal template](https://github.com/linclark/wasi-proposal-template).

**Comment by linclark** [comment]
Unfortunately I haven't updated the proposal template yet to reflect the rename of the format. The `wai.md` file should be `wit.md` instead.

**Comment by sunfishcode** [comment]
Indeed, and the tools are still called wai-bindgen and wai-abi, and are still expecting wai. When these are updated, I'll update the proposal here.

**Comment by sunfishcode** [comment]
wit-bindgen is now updated for the rename, so I've now updated this to rename wai to wit. The remaining piece here is https://github.com/WebAssembly/wasi-tools/pull/1.

**Comment by sunfishcode** [comment]
This has been open for a few weeks, so I'm going to merge this now, so that we can iterate from here with pull requests. If anyone has comments on this, feel free to comment here, or file new issues in the issue tracker.

**Pull request merged**
