### PR TITLE
Unquote type, weird to quote it.

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by sunfishcode** [comment]
The quotes are there because `type` is a keyword in wit, and quotes are the way to explicitly make it an identifier.

**Comment by lygstate** [comment]
> 



> The quotes are there because `type` is a keyword in wit, and quotes are the way to explicitly make it an identifier.

Keyword as a type name or rename it to avoid conflict?
I see no language use quotes keyword to avoid the conflict.

**Comment by sunfishcode** [comment]
This is just the wasi-filesystem proposal repo. To propose a change to the syntax; please file an issue in [the interface types repo](https://github.com/WebAssembly/interface-types).

**Comment by sunfishcode** [comment]
The `type` in question is now using wit-bindgen's new syntax, which is `%type`.

**Pull request closed without merging**
