### PR TITLE
Rename atflags to rflags, to match oflags.

### PR DESCRIPTION
**Pull request by lygstate**
Maybe open_flags and resolve_flags are better?

The comment have not mention about `at`, but `resolved`

### CODE REVIEW

**Comment by sunfishcode** [comment]
I'm not strongly attached to it, but I picked `at` to more closely resemble POSIX, where similar flags are called `AT_*`, such as `AT_SYMLINK_FOLLOW`. It also reflects the "at" naming of the functions that use these flags; that's something that could be mentioned in the comment. Could you say more about the relationship to oflags here?

**Comment by sunfishcode** [comment]
It's subjective, but to my eyes, `oflags` at `atflags` resembling `O_*` and `AT_*` flags in POSIX is more useful than being consistent about whether things are abbreviations.

Would it clarify things to rename it to `at_flags`, with an underscore? That would emphasize the relationship to the `_at` functions.

**Comment by lygstate** [comment]
> It's subjective, but to my eyes, `oflags` at `atflags` resembling `O_*` and `AT_*` flags in POSIX is more useful than being consistent about whether things are abbreviations.
> 
> Would it clarify things to rename it to `at_flags`, with an underscore? That would emphasize the relationship to the `_at` functions.

Oh, it's comes from posix, how about o_flags at_flags for consistence, as it's comes from resembling `O_*` and `AT_*` flags in POSIX

**Comment by sunfishcode** [comment]
> Oh, it's comes from posix, how about o_flags at_flags for consistence, as it's comes from resembling O_* and AT_* flags in POSIX

This looks good to me. And it happens that as part of the update to kabob case for wit-bindgen, these names are now named `at-flags` and `o-flags`, with a dash where we discussed an underscore above, but I believe preserve the spirit here.

**Pull request closed without merging**
