### PR TITLE
Fix a couple of typos in README.md

### PR DESCRIPTION
**Pull request by dylanahsmith**

### CODE REVIEW

**Review by pchickey — APPROVED** [review]

**Comment by pchickey** [comment]
Thanks. These fixes need to carry through to the generated markdown. You can either run the tool as given by the CI failure, or else just fix the generated markdown by hand so it matches.

**Comment by dylanahsmith** [comment]
The changes are in README markdown.

`git grep indluding` and `git grep operatings` don't show these typos elsewhere in the source code, so I don't see where anything generates this markdown or anything that is generated from it.

The CI failure on this branch is consistent with the CI failure in the latest commit on main.

**Comment by sunfishcode** [comment]
Yes, please ignore the CI failures for now; the tooling we use is in transition. Once we finish the transition to resources, this will all get fixed.

**Comment by sunfishcode** [comment]
Thanks!

**Pull request merged**
